# Generated by Django 5.0.6 on 2024-06-05 05:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order_Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Order_Placed', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
