# Generated by Django 5.0.6 on 2024-06-05 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_book',
            name='Select_Book_and_Place_Order',
            field=models.CharField(choices=[('B1', 'The Power of your subconscious mind'), ('B2', "Don't Believe everything you think"), ('B3', 'The Alchemist'), ('B4', 'The Silence Patient'), ('B5', 'Focus on what matters'), ('B6', '11 Rules for Life'), ('B7', 'Lucifer was Innocent')], default='B7', max_length=2),
        ),
    ]
