# Generated by Django 5.0.6 on 2024-06-05 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_rename_select_book_and_place_order_order_book_select_book_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_book',
            name='Confrim_book',
            field=models.ImageField(default='', upload_to='book_imgs/'),
        ),
    ]
