# Generated by Django 5.0.6 on 2024-06-06 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_rename_confrim_book_order_book_confirm_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_book',
            name='Select_Price',
            field=models.CharField(choices=[('$35', '$35'), ('$48', '$48'), ('$56', '$56'), ('$89', '$89')], default='$48', max_length=3),
        ),
    ]
