# Generated by Django 5.0.6 on 2024-06-08 18:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order_Gadget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Order_Placed', models.DateTimeField(default=django.utils.timezone.now)),
                ('Select_Gadget', models.CharField(choices=[('Gad1', 'KEYBOARD - AntEports'), ('Gad2', 'MOUSE - HyperX'), ('Gad3', 'MOUSE - Logitech'), ('Gad4', 'KEYBOARD - MegaGee'), ('Gad5', 'KEYBOARD - RedDragon'), ('Gad6', 'MOUSE - ZebronicsTransformer')], default='Bot1', max_length=4)),
                ('Select_Quantity', models.CharField(choices=[('01', '1'), ('02', '2'), ('03', '3'), ('04', '4'), ('05', '5'), ('06', '6'), ('07', '7'), ('08', '8')], default='01', max_length=2)),
                ('Select_Price', models.CharField(choices=[('$35', '$35'), ('$48', '$48'), ('$56', '$56'), ('$89', '$89')], default='$48', max_length=3)),
                ('Confirm_Gadget', models.ImageField(default='', upload_to='gadget_imgs/')),
            ],
        ),
    ]
