# Generated by Django 5.0.6 on 2024-06-08 10:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order_Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Order_Placed', models.DateTimeField(default=django.utils.timezone.now)),
                ('Select_Wallet', models.CharField(choices=[('Wal1', 'Al Fascino'), ('Wal2', 'HornBull Wallets for Men'), ('Wal3', 'Napa Hide'), ('Wal4', 'Rigo Hill'), ('Wal5', 'Wild Horn')], default='Wal1', max_length=4)),
                ('Select_Quantity', models.CharField(choices=[('01', '1'), ('02', '2'), ('03', '3'), ('04', '4'), ('05', '5'), ('06', '6'), ('07', '7'), ('08', '8')], default='01', max_length=2)),
                ('Select_Price', models.CharField(choices=[('$35', '$35'), ('$48', '$48'), ('$56', '$56'), ('$89', '$89')], default='$48', max_length=3)),
                ('Confirm_Wallet', models.ImageField(default='', upload_to='Wallet_imgs/')),
            ],
        ),
    ]
